apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - serviceaccounts.yaml
  - workloads.yaml

images:
  - name: auth-image
    newName: 617309006489.dkr.ecr.us-east-1.amazonaws.com/togglemaster/auth-service
    newTag: 656bcaa0ca87b731af3413093d999d35bf17b4d5
  - name: flag-image
    newName: 617309006489.dkr.ecr.us-east-1.amazonaws.com/togglemaster/flag-service
    newTag: 656bcaa0ca87b731af3413093d999d35bf17b4d5
  - name: targeting-image
    newName: 617309006489.dkr.ecr.us-east-1.amazonaws.com/togglemaster/targeting-service
    newTag: 656bcaa0ca87b731af3413093d999d35bf17b4d5
  - name: evaluation-image
    newName: 617309006489.dkr.ecr.us-east-1.amazonaws.com/togglemaster/evaluation-service
    newTag: 656bcaa0ca87b731af3413093d999d35bf17b4d5
  - name: analytics-image
    newName: 617309006489.dkr.ecr.us-east-1.amazonaws.com/togglemaster/analytics-service
    newTag: 656bcaa0ca87b731af3413093d999d35bf17b4d5