apiVersion: v1
kind: ServiceAccount
metadata:
  name: evaluation-service
  namespace: togglemaster
  labels:
    app.kubernetes.io/name: evaluation-service
    app.kubernetes.io/part-of: togglemaster
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service
  namespace: togglemaster
  labels:
    app.kubernetes.io/name: analytics-service
    app.kubernetes.io/part-of: togglemaster
